name: DamagerRewards
version: '1.0.1.4'
main: cn.i7mc.damagerRewards.DamagerRewards
api-version: '1.20'
authors: [i7mc]
description: 'MythicMobs伤害排名奖励插件'
website: 'https://i7mc.cn'
depend:
  - MythicMobs
softdepend:
  - PlaceholderAPI
commands:
  damagerrewards:
    description: '插件主命令'
    aliases: [dr]
    usage: '/dr [reload]'
permissions:
  damagerrewards.admin:
    description: '管理员权限'
    default: op
  damagerrewards.reload:
    description: '重载配置权限'
    default: op